# Generated by Django 4.2.7 on 2026-05-15 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0001_initial'),
        ('accounts', '0001_initial'),
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_phone', models.CharField(db_index=True, max_length=15)),
                ('user_mac', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkout_request_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('mpesa_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.package')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='routers.router')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotspotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('mikrotik_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdevice')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routers.router')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='BandwidthUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bytes_in', models.BigIntegerField(default=0)),
                ('bytes_out', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='billing.hotspotsession')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.AddIndex(
            model_name='hotspotsession',
            index=models.Index(fields=['is_active', 'end_time'], name='billing_hot_is_acti_778b2b_idx'),
        ),
    ]
