# Generated by Django 4.2.7 on 2026-05-15 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField(help_text='Format: DD HH:MM:SS')),
                ('bandwidth_limit_up', models.IntegerField(default=1024, help_text='In kbps (e.g. 1024 for 1Mbps)')),
                ('bandwidth_limit_down', models.IntegerField(default=1024, help_text='In kbps (e.g. 1024 for 1Mbps)')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
